### ISSUE TITLE
Add one CVPR 2022 Inpainting paper

### ISSUE THREAD

**Issue by cddlyf** [1900zyh/Awesome-Image-Inpainting#8]
@1900zyh  Hi Yanhong, please help add one CVPR 2022 paper

[Reduce Information Loss in Transformers for Pluralistic Image Inpainting](https://arxiv.org/pdf/2205.05076.pdf), Liu et al., In CVPR 2022 [[code]](https://github.com/liuqk3/PUT)

**Comment by zengyh1900** [comment]
@cddlyf Thank you for your information. I have updated it :)
