### ISSUE TITLE
Suggestion to sort paper in the year-descending order

### ISSUE THREAD

**Issue by cddlyf** [1900zyh/Awesome-Image-Inpainting#9]
Hi @1900zyh yanhong, I suggest you to help sort the paper in a year-descending order, so that it is easier to find the latest progress in the field.

**Comment by zengyh1900** [comment]
Hi @cddlyf,

Thank you for your suggestion! I have updated this collection, 
1. I have sorted the paper in a year-descending order like you suggested. 
2. I have provided a [script](https://github.com/zengyh1900/Awesome-Image-Inpainting/blob/master/.dev_scripts/main.py) to generate automatically [collection.csv](https://github.com/zengyh1900/Awesome-Image-Inpainting/blob/master/.dev_scripts/collection.csv) from `README.md` or vice versa.
